[package]
name = "wsl-dirutils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.4"
once_cell = "1.18.0"
regex = "1.9.3"
wslpath = "0.0.2"
